#Redsox Rewards Login Info
username: 
password: 
#Browser deviceGUID
guid: 
#Telegram BotFather Information 
telegram_url: 
#If posting to a bot chat enter your bot's user ID. If posting to a public channel use '@channelname'
user_id: 
# Length of time to wait between item checks
sleepTimer: 120
#Log Level (info, error, debug)
logLevel: debug